lsof-org/lsof

README.md
=> README.md: more minor changes

README.md
=> README.md: call us "lsof-org at GitHub team"

lsof.h, usage.c
=> Update URLs in -v output and -h output

Configure
and how do we make new tarballs?
=> allow FreeBSD 13

00DIST
=> docs: update 00DIST

.cirrus.yml, README.md
=> Introduce cirrus ci to run test cases on FreeBSD 

.travis.yml, README.md
=> Introduce travis-ci to run test cases on Linux

README.md, lsof.h
=> make "master" as the default branch

README.md, lsof.h
=> Rename the repository

README.md
=> Use the new repo name in the URL for travis CI badges

README.md
=> Use the new repo name in the URL for coveralls badge

00DIST, Lsof.8, dialects/linux/dnode.c, dialects/linux/dproc.c, dialects/linux/tests/Makefile, dialects/linux/tests/case-20-eventfd-endpoint.bash, dialects/linux/tests/eventfd.c, lsof.h, main.c, proc.c, proto.h
=> endpoint(eventfd): implementat [-+]E option for eventfd (Linux 5.2 or higher)

.gitignore
=> gitignore: add more executables used from test cases

.cirrus.yml
update to modern FreeBSD images
=> update FreeBSD images

00CREDITS, 00DIST, dialects/freebsd/dnode.c, dialects/freebsd/dnode2.c, dialects/freebsd/dproc.c, dialects/freebsd/dsock.c
[FreeBSD] Fixes #69 and other issues.
=> [FreeBSD] Merge freebsd patches

00CREDITS, 00DIST
=> docs: update 00DIST and 00CREDITS

00DIST, Lsof.8
=> man page: enumerate abbreviated flags printed with +f g

dialects/linux/dproc.c, dialects/linux/dsock.c
=> [linux] supress warning reported by clang

README.md
=> [freebsd] hide cirrus badges

HOW_TO_RELEASE.rst
=> Add a document describing steps for making a new release

HOW_TO_RELEASE.rst
=> Fix typos in HOW_TO_RELEASE.rst

support/GenericSubdir
=> [linux] don't distribute version.h of the dialect

.gitignore
=> .gitignore: add lib/Makefile

00DIST
=> docs: clean up whitespaces in 00DIST

README.md
=> Add the status badge of circleci

00CREDITS
=> docs: update 00CREDITS (#217)

00CREDITS
=> docs: update 00CREDITS (#226)

dialects/freebsd/dlsof.h
=> [FreeBSD] Unconditionally define HASKQUEUE

src/print.c
- relates to https://github.com/Homebrew/homebrew-core/pull/153917
=> fix argument mismatch for gethostnm

Lsof.8
=> man lsof: mention /etc/services for -P option

00DIST, lib/dialects/linux/dproc.c, lib/dialects/linux/tests/case-20-inet6-ffffffff-handling.bash, lib/dialects/linux/tests/case-20-pidfd-pid.bash
=> Fix pidfs display linux 6.9

docs/maintaining.md
People can be confused with my name on the list of maintainers.
=> Remove myself from the team of linux dialect

Configure
* Add FreeBSD 16
* Remove FreeBSD 12 (EoL on December 31, 2023)
=> [freebsd] Update supported FreeBSD versions
