lsof-org/lsof

README.md

Use the old repo name in URLs for CI badges

---

tests/LTlib.c

"major" is defined in sys/sysmacros.h of glibc.
sys/types.h included sys/sysmacros.h.
However, newer glibc shipped as part of Fedora29 removed the directive
for including sys/sysmacros.h from sys/types.h. As the result, we cannot
compile tests/LTlib.c on Feodra29 because of no major definition.
As instructed in sys/types.h, we will include sys/sysmacros.h directly
in this change.
The original issue is reported by @barsnick at #40.

test cases: include <sys/sysmaros.h> to compile tests/LTlib.c on newer GNU/Linux distributions

---

.gitignore
00DIST
Lsof.8
dialects/linux/dlsof.h
dialects/linux/dmnt.c
dialects/linux/dnode.c
dialects/linux/dstore.c
dialects/linux/tests/Makefile
dialects/linux/tests/case-10-mqueue.bash
dialects/linux/tests/mq_open.c
lsof.h

A file descriptor is used for implementing a POSIX message queue on
Linux. lsof reports the file descriptor as a REGular file.
This change introduce "PSXMQ" as a new file type for the
file descriptor.
Currently implementation requires mqueue file system must be
mounted to resolve the file type. It is mounted at /dev/mqueue
by default on Fedora. It seems that the file system is not mounted
by default on Ubuntu.

Support POSIX message queue

---

.cirrus.yml
00DIST
Configure
dialects/freebsd/dlsof.h

This is based on #51 made by @ lrosenman.
* Simplify the commit sequence.
* Add prefix [freebsd] to some logs.
* Split the commits about cirrus.

Freebsd current based on pr 51

---

00DIST
Lsof.8
README.md

We have to update the URLs and contact addresses in our documents so we can receive bug ports.
This is the first step.

docs: update URLs and contact addresses in man page

---

00DIST
Lsof.8
lsof.h
main.c
store.c
tests/case-20-repeat-count.bash

e.g.
$ ./lsof -r1c3 -p 1
This command line lists files currently opend by the process having 1
as pid 3 times with 1 sec interval.
This enhancement helps us to run lsof under valgrind.

Allow to specify max iteration count to -r option

---

dialects/freebsd/dlsof.h

Without this header the build fails on latest 12-STABLE and possibly 13-CURRENT.

Add missing header to FreeBSD dlsof.h

---

00DIST
dialects/linux/dproc.c

In process_id(), a local variable `ls' is passed to process_proc_node()
if `pn' is non-zero. However, there is a control-flow where `pn' is set to 1
but `ls' is not set. Valgrind detected this.

[linux] fix accessing an uninitialized local variable

---

00DIST
dialects/linux/dsock.c
dialects/linux/tests/Makefile
dialects/linux/tests/case-20-ux-socket-endpoint-unaccepted.bash
dialects/linux/tests/ux.c

Close #74 reported by @jolmg.
When printing the end point of the unix domain socket whose counter part is not
accepted yet by server side, lsof with +E option crashed with NULL pointer
dereference.

 [linux] fix a crash when printing the endpoint for unaccepted unix socket with +E option

---

.gitignore

Without '/', all the Makefiles are ignored, including
dialect-specific ones (unless they are already added),
which can be hard-to-pin source of confusion.

.gitignore: Ignore top-level Makefile only

---

misc.c

Lsof runs sub processes for implementing non-blocking
stat, lstat, and readlink. Lsof main process uses pipes fo
for coummunicating with the sub processes.
Valgrind reports a buffer used in the pipe communication
isn't initialized:
$ sudo valgrind -v --track-origins=yes ./lsof  > /dev/null
==13857== Memcheck, a memory error detector
==13857== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13857== Using Valgrind-3.14.0-353a3587bb-20181007X and LibVEX; rerun with -h for copyright info
==13857== Command: ./lsof
...
==13858== Rerun with --leak-check=full to see details of leaked memory
==13858==
==13858== ERROR SUMMARY: 199 errors from 1 contexts (suppressed: 0 from 0)
==13858==
==13858== 199 errors in context 1 of 1:
==13858== Syscall param write(buf) points to …

Fill the buffer using pipe communication with zero

---

00DIST
dialects/linux/dsock.c

[linux] decode the name of DCCP socket type

---

00DIST
Configure
Lsof.8
dialects/linux/dlsof.h
dialects/linux/dsock.c
dialects/linux/tests/case-10-ux-socket-state.bash
lsof.h

Lsof can print the state of TCP socket like:
nc      22247 yamato    3u  IPv4 471409      0t0        TCP localhost:38802->localhost:9999 (ESTABLISHED)
This change exnteds this feature to support unix domain sockets.
LISTEN, UNCONNECTED, CONNECTING, CONNECTED, DISCONNECTING,
and UNKNOWN can be taken as a state.
An example of output:
evince    17333  yamato    1u  unix 0x0000000054183795      0t0  89141 type=STREAM (CONNECTED)
This feature is enabled by default.
To turn off printing state information, use -T option.
Close #76.

[linux] print the connection state of unix domain socket

---

00DIST
main.c
tests/case-20-handle-missing-files.bash

Close #90.
The original behavior (taken from #90):
$ lsof /bin/ls
...
$ lsof /bin/ls /bin/lsxxx
lsof: status error on /bin/lsxxx: No such file or directory
...
$ lsof /bin/lsxxx
lsof: status error on /bin/lsxxx: No such file or directory
lsof 4.91
latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-E] [+|-e s] [+|-f[gG]]
[-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
Just displaying "No such file or directory" is enough for all the …

Don't display usage even when even a non-existing file is passed

---

00CREDITS
00DIST
dialects/linux/Makefile

In a reproducible build all varied information is removed.
This patch does so, by checking if the standard [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/) variable is set.
If it is, we are attempting a reproducible build and will strip varying information.

[linux] Allow reproducible builds

---

Customize

Fixes a very minor grammatical error I found in the Customize script instructions for WARNINGSTATE.

Fixed minor grammatical error in instructions

---

Lsof.8

The "piped to" description is flat wrong, because "kill" doesn't read anything from stdin.
Saying that one command line option "selects" another is weird; "implies" would be clearer, both times it's mentioned.
Also added some examples.

Improve man page

---

tests/LTbasic.c
tests/LTdnlc.c
tests/LTnlink.c
tests/LTszoff.c
tests/LsofTest.h

The way that test strings were formatted could lead to tests failing
when run with large inode-numbers (i >= 2^32). This is fixed by
formatting with uint64 values intead of unsigned ints.

Fix tests for large inode-numbers (i >= 2^32).

---

00CREDITS
00DIST
dialects/linux/dsock.c
dialects/linux/tests/case-20-inet6-ffffffff-handling.bash

Close #102
Close #109
The listen address and port of an AF_INET6 socket were not display if
the socket listened at an ipv6 address including ffff:ffff.
Here is a command session demonstrating the bug:
[1] 6762
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
nc      6762 yamato    0u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    1u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    2u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    3u  sock    0,9      0t0 5833594 protocol: TCPv6
The last line should be:
nc      6762 yamato    3u  IPv6 5833594      0t0  TCP [abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62]:8888 (LISTEN)
The original code decoding an ipv6 address uses UINT32_MAX constant
incorrect way.
@zhrf2020 reported this bug in #102. …

[linux] handle ffff:ffff in ipv6 addr correctly

---

.cirrus.yml
README.md

https://github.com/lsof-org/lsof/pull/94#issuecomment-639180877h
lrosenman commented on Jun 5
@masatake the FreeBSD CI is failed due to the Cirrus stuff using outdated images.
I'll see if I can figure out how to fix that for all 3 FreeBSD versions.
Till we find the way to update the images, disable the testing.

[freebsd] cirrus-ci: disabled

---

00CREDITS
00DIST
main.c
tests/case-20-offset-field.bash

Close #118.
-Fo option is for printing file offset. For regular files, the option didn't work.
Here is a command session demonstrating the fix:
90586 o0t0
87 o0t101
84 o0t103
...
@JustAnotherArchivist reported this bug in #118.

Make -Fo option work

---

Lsof.8

Fix man page definition of the `o` field on programmatic output

---

00CREDITS
00DIST
Lsof.8
store.c

Close #103.
The version 4.88 introduced the change for selecting the file
descriptor field by default. However, the change is not
suitable for users who wants to print only PID field.
@po5857 suggests the use case.

Don't select the file descriptor field by default.

---

.gitignore
00DIST
dialects/linux/dproc.c
dialects/linux/tests/Makefile
dialects/linux/tests/case-20-epoll.bash
dialects/linux/tests/epoll.c

[linux]: enumerate fds monitored by an eventpoll fd
With this change, lsof prints an eventpoll fd in the following form:
[eventpoll:<fd0>,<fd1>,...,<fdn>...]
Here fdX is a file descriptor monitored by the eventpoll fd.
If an eventpoll fd monitors too many file descriptors, lsof
truncates the list of fds. "..." at the end of list implies
the truncation.
Example output:
COMMAND PID USER   FD      TYPE DEVICE SIZE/OFF  NODE NAME
systemd   1 root   10u  a_inode   0,13        0 11624 [eventpoll:11,12]
systemd   1 root   11r      REG    0,4        0 17680 /proc/1/mountinfo
systemd   1 root   12r  a_inode   0,13        0 11624 inotify
systemd monitors fd 11 and fd 12 via eventpoll fd 10.

[linux] enumerate fds monitored by an eventpoll fd

---

dialects/n+obsd/dproc.c

[n+obsd] Corrected end of comment.

[n+obsd] issue #138 Syntax error in dialects/n+obsd/dproc.c

---

tests/Makefile

GNU Guix makes the ‘standard’ and ‘optional’ tests and expects both to
return non-zero exit status on failure. However, only ‘make silent’ did.
This led to test failures going unnoticed.
Make all targets properly signal failure (and even more obvious how much
boilerplate they share :-).

tests: Don't ignore failures

---

00DIST
NEW/usage.c
dialects/aix/Makefile
dialects/darwin/kmem/Makefile
dialects/darwin/libproc/Makefile
dialects/du/Makefile
dialects/freebsd/Makefile
dialects/hpux/kmem/Makefile
dialects/hpux/pstat/Makefile
dialects/linux/Makefile
dialects/n+obsd/Makefile
dialects/n+os/Makefile
dialects/osr/Makefile
dialects/sun/Makefile
dialects/uw/Makefile
usage.c

LSOF_CCDATE is used to embed the build time/date string into the lsof binary.
This string is displayed as part of 'lsof -v' output. However, having that
embedded string breaks reproducible builds - we want to ensure that subsequent
builds (using the same exact build environemnt) produce the same exact binary,
bit-for-bit.
Debian has a patch that allows overriding the variable, similar to what lsof allows
for LSOF_HOST (and others). Let me know if you'd prefer that patch. However,
I'm of the opinion that LSOF_CCDATE should just be dropped completely. We
can see the version to tell us what the corresponding source code is, and we have
file timestamps to tell us when a binary was installed. LSOF_CCDATE provides
no security, as an attacker could hardcode the older date/time string in their …

Drop LSOF_CCDATE in order to ensure reproducible builds

---

lsof_fields.h

In https://github.com/lsof-org/lsof/commit/811dc78cc6404cb39d82bf01728cfdf38f097af1 the output format was changed to not select the `f` field by default, however the field description in `lsof_fields.h`, as seen in `-F?` output still included the `(always selected)` text.

Fix FD field description

---

00CREDITS
00DIST
misc.c

Close #160.
The original code passes char[] buffer to stat().
This can be cause a SIGBUS.
#160 reported an actual crash on armv7a + glibc-2.33 platform.
See also https://sourceware.org/bugzilla/show_bug.cgi?id=27993.
The issue is reported by @10ne1.

Adjust alignment of buffer passed to stat()

---

00DIST
Configure
dialects/freebsd/dnode.c
dialects/freebsd/dnode1.c
dialects/freebsd/dproto.h

Fixes for the ISO9660 filesystem. Adds support for msdosfs.

FreeBSD isofs fixes and msdosfs support

---

00DIST
dialects/linux/dlsof.h
main.c

At the starting up, lsof closes its file descriptors greater
than 2 by calling close(2) repeatedly. As reported in https://github.com/lsof-org/lsof/issues/186,
it can take long time. Linux 5.9 introduced close_range(2).
The new system call can close multiple file descriptors
faster.
Close https://github.com/lsof-org/lsof/issues/186 for Linux. @qianzhangyl reported the issue.

[linux] use close_range instead of calling close repeatedly 

---

00DIST
lib/Makefile.skel

This patch has been added in the context of buildroot sixteen years ago, here is an extract of
https://git.buildroot.net/buildroot/commit/package/lsof?id=aca398bb7fa956dc44e1442969c4a2a425780997:
> compile against the cross toolchain, not the host
[Retrieved from: https://git.buildroot.net/buildroot/tree/package/lsof/0001-makefile.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

lib/Makefile.skel: fix AR and RANLIB when cross-compiling

---

00DIST
dialects/linux/machine.h

This patch has been added in the context of buildroot fifteen years ago: https://git.buildroot.net/buildroot/commit/package/lsof?id=c1efa9b291f0aa1453ea6359cc6638c0e75b2ca7
[Retrieved from: https://git.buildroot.net/buildroot/tree/package/lsof/0002-remove-susvlegacy-funcs.patch]
While at it also fix indentation in 00DIST
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

dialects/linux/machine: remove sysvlegacy function

---

00DIST
lib/Makefile.skel

This reverts commit e3e81bbe865d61b738cbd6fd4b973d33508db5a9. (#194)
Grisha Levit (@schrodinger) reported the build error with introducing
the commit.
Close #197.

Revert "lib/Makefile.skel: fix AR and RANLIB when cross-compiling"

---

.circleci/config.yml

[linux] circleci: install libtirpc-devel package before testing

---

00DIST
arg.c
dialects/linux/Makefile
dialects/linux/dfile.c
dialects/linux/dmnt.c
dialects/linux/dnode.c
dialects/linux/dproc.c
dialects/linux/dsock.c
dialects/linux/dstore.c
lsof.h
main.c
misc.c
node.c
print.c
proc.c
store.c
usage.c
util.c

Close #206.
I introduced -Wall option in this pull request.
As the result, we'll get more warnings.

Various non-critical fixes

---

00CREDITS
00DIST
dialects/linux/dsock.c

As promised in #208 here's that minor hash function change.
The values in the change are chosen in a way that similar values from different components that make up the hash are added with a slight shift relative to each other.

[linux] Avoid some easy collissions for udp/udp6 sockets when hashing

---

00CREDITS
00DIST
dialects/linux/dsock.c

I suggest to increase the number of ipcbckets. On an fresh installed Ubuntu VM there are over 200 sockets used.
BenBE mentioned this problem here: https://github.com/lsof-org/lsof/pull/212#issuecomment-1113964661 .
I also fixed a small typo.

[linux] Changing the number of ipcbuckets to 4096

---

dialects/darwin/kmem/dlsof.h

gcc-10 and llvm-11 changed the default from -fcommon to -fno-common:
https://gcc.gnu.org/PR85678
As a result build fails as:
duplicate symbol '_Cfp' in: ddev.o dfile.o
`Cfp` is already explicitly defined in `dstore.c`. The change turns
header definitino into declaration.

darwin: fix build with -fno-common (Cfp redefinition)

---

00DIST
dialects/linux/Makefile

At openSUSE we have found out that lsof is still not completely reproducible due to the hostname being included in the resulting binary. This PR allows for reproducible hostname.
https://bugzilla.suse.com/show_bug.cgi?id=1199709

linux: Make build reproducible by default

---

dialects/darwin/libproc/dlsof.h

Defining global variables in headers is error prone and can break
builds with -fno-common flag enabled:
duplicate symbol '_Cfp' in:
ddev.o
dfile.o
The issue is fixed in libproc backend in the same way as pr #221.

darwin: fix global variable definition in dlsof.h

---

.circleci/config.yml

The commands are taken from .travis.yml.
Install gem, skip CC env check because it is unset. Pass
COVERALLS_REPO_TOKEN env to lcoveralls.
Fix #191.

circleci: setup coverage reporting

---

00DIST
dialects/darwin/libproc/dstore.c

In previous attempt to handle -fno-common, I fixed the multiple declaration issue, but I forgot to add the declaration in dstore.c.

More darwin fixes

---

00DIST
Configure
dialects/darwin/kmem/dlsof.h
dialects/darwin/kmem/machine.h
dialects/darwin/libproc/machine.h

The /usr/include path is missing on modern Darwin systems. The intention
of hardcoding the path is unknown. Fixes issue #234.

[darwin] fix: remove /usr/include prefix from include

---

.circleci/config.yml

Set LSOF_INCLUDE to search libproc.h in macOS sdk
Disable unit tests until issue #236 is fixed

[darwin] circleci: add ci config for macOS catalina target

---

.circleci/config.yml
.gitignore
00DIST
dialects/linux/dproc.c
dialects/linux/tests/Makefile
dialects/linux/tests/case-20-mmap.bash
dialects/linux/tests/mmap.c
dialects/linux/tests/mount-and-mmap.bash

In circumstances the target process in different mount namespace
from lsof itself, applying stat(2) directly gets failed,
with error message 'stat: No such file or directory'.
Thus, fork a child process and move it into the mount namespace
of the target process before applying stat(2). In this way, correct
information can be obtained.
Signed-off-by: huteng.ht <huteng.ht@bytedance.com>
#238

[linux] obtain correct information of memory-mapped file.

---

dialects/linux/tests/mq_open.c

Signed-off-by: Li zeming <zeming@nfschina.com>
Remove a semicolon to make the statement look better.

linux/tests: remove a ';'

---

Configure

Clang 15 makes -Wimplicit-int an error by default.
Before this fix, configure would think localtime() and strftime() support was not present.
Signed-off-by: Sam James <sam@gentoo.org>

Configure: fix configure tests broken with Clang 15 (-Wimplicit-int)

---

.cirrus.yml
README.md

Also:
- remove git from the list of packages to install (we do not need it,
the clone is already done for us by Cirrus-CI)
- remove the timeout override as the build and test will complete within
Cirrus-CI's default
- request only 1 CPU as we do not take advantage of parallelism so there
is no reason to have a spare idle vCPU around
- rename the main script to "build" and split a test script out so that
we can more easily differentiate build failures from test failures
- keep a FreeBSD 11 image for now (even though EOL) until tests pass
consistently on supported releases
11.4:
```
STARTING TEST ( dialect neutral )
=============================================================================
case-00-hello ... ok
case-01-version ... ok
case-13-classic ... failed
case-14-classic-opt ... ok …
```

cirrus-ci: update for FreeBSD 13.0 and 12.2

---

.cirrus.yml

- 13.1 is released, 13.0 is EOL
- 11.4 is EOL

cirrus-ci: update FreeBSD versions

---

00PORTING
Configure
dialects/freebsd/dlsof.h

sys/files.h exports a userland interface. It no longer requires _KERNEL to be defined to access it, and hasn't since approximaely 2002 or so. Remove all the cruft we used to allow us to include with _KERNEL. We also no longer need to probe sys/systm.h to see if it has pause or not, since it's not drawn in.

[FreeBSD] sys/files.h no longer needs _KERNEL defined to include it

---

Lsof.8

I had to go read the source code to figure out what the FD's listed with leading * represented...

Describe fd number truncation in output

---

Configure

Implicit int and implicit function declarations have been removed from the C language with the 1999 language standard.  Add the missing int type specifier and #include <stdio.h> for printf.

Avoid C89-only constructs in Configure

---

.gitignore
Configure
Makefile.am
autotools/autotools.h.in
configure.ac
dialects/n+obsd/dlsof.h
dialects/n+obsd/dmnt.c
dialects/n+obsd/dnode.c
dialects/n+obsd/dnode1.c
dialects/n+obsd/dproc.c
dialects/n+obsd/dsock.c
dialects/n+obsd/dstore.c
dialects/n+obsd/machine.h
lib/Makefile.skel
lib/prfp.c
lib/rmnt.c
lib/rnam.c
lib/rnch.c
lib/rnmh.c
lib/rnmt.c
m4/header.m4
usage.c

I merged patches from http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/lsof/patches/ for #219. I have tested on NetBSD 9.3. Progress:

Import NetBSD patches from pkgsrc

---

dialects/linux/tests/case-20-epoll.bash
dialects/linux/tests/epoll.c

In case file descriptor 3 and 4 are being used already, the executable created by epoll.c exits with exit code 1, and prints the message -
epoll_ctl<6>: Invalid argument
causing case-20-epoll.bash to FAIL.

[linux] Do not hard-code fd numbers in epoll test

---

dialects/aix/dproc.c

IBM lsof was compiled on AIX 6.1, and targets are AIX 6.1, 7.1 and 7.2.
On AIX 7.1, we have "lsof: WARNING: compiled for AIX version 6.1.0.0; this is 7.1.0.0.", even if all is ok.
This test, for old AIX versions under 5.0 on lines 245 and 246,  need to be done everywhere.
I don't have compilers and so on to test that new code, but could be ok if your compiler accept it.

Test on all AIX versions to solve issue #187

---

Makefile.am
configure.ac

Since liblsof is still in alpha stage, therefore I've set the flag to disabled by default..
Fixes #299

Add configuration flag for enabling liblsof (#299)

---

configure.ac

This change makes building on Linux reproducible, closing issue #310.

[linux] Do not embed kernel version in CFLAGS

---

lib/misc.c

Add an optimized fallback in closefrom_shim() for Linux, if the platform doesn't support closefrom or close_range.
Iterate /proc/self/fd and close anything which is not that directory itself.
This can save significant time if "ulimit -n" (max open files) is very high. For example, in some Docker containers the limit can be 2^30 (~ 1 billion), and lsof may take 10-30 minutes to start up.

[linux] closefrom_shim: Add optimized fallback for platforms without closefrom or close_range

---

lib/dialects/linux/dproc.c

**Describe the bug**
Since lsof-4.96.0, run lsof with old linux kernel (e.g. linux-2.6), 
lsof would print error message "stat: No such file or directory"
when visiting memory-mapped files; but /bin/stat could visit it without issue.
lsof-4.95.0 and earlier does not have this issue.
- 4.99.4 fail
- 4.99.3 fail
- 4.96.0 fail
- 4.95.0 pass
- 4.92.0 pass
In old linux kernel (e.g. linux-2.6) which does not have this feature: Commit 
[6b4e306aa3dc](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6b4e306aa3dc) ("ns: proc files for namespace naming policy."), means this path 
"/proc/self/ns" is not existed. Since lsof-4.96.0 with Commit dbad15094a98 ("
[linux] obtain correct information of memory-mapped file."), compare_mntns() 
would misunderstand it is in a …

[linux] fix: memory-mapped file, stat: No such file or directory

---

lib/dialects/linux/dproc.c

The logic in process_id() requires a reset of
the efs variable on every iteration through the
while ((fp = readdir(fdp)) loop.
Failure to do that can land us in a situation
where efs=1 from a previous iteration and
pn=1 from the current iteration.
This fixes issue 335 ( lsof SIGSEGV )  https://github.com/lsof-org/lsof/issues/335

Fix null pointer exception
